########################################################################################################
########################################################################################################
########################################################################################################
########################################################################################################
#######################                                                #################################
####################### AUTHOR: SALVADOR JESÚS MEGÍAS ANDREU           #################################
####################### EMAIL: salvadorjmegias@gmail.com               #################################
####################### UNIVERSITY EMAIL: salvadorjesus@correo.ugr.es  #################################
#######################                                                #################################
########################################################################################################
########################################################################################################
########################################################################################################
########################################################################################################



# HOW TO USE TO EXECUTE AND LAUNCH: uvicorn api:api --reload

# If you don't find the uvicorn module installed, use the following:
# HOW TO USE TO EXECUTE AND LAUNCH: python -m uvicorn api:api --reload

# The OPENAPI documentation generated by FastAPI can be accessed directly
# automatically at the following link (provided you have launched uvicorn with the command above): http://127.0.0.1:8000/docs


from fastapi import FastAPI
import random

api = FastAPI(title= "TFG Salvador Jesús Megías Andreu")

@api.get("/getTemperature")
async def getTemperature():
    return float(random.randint(22*10,50*10)/10)

@api.get("/getFlow")
async def getFlow():
    return float(random.randint(1*10,7*10)/10)


@api.get("/getIlockFlow")
async def getIlockFlow():
    return int(12)

@api.get("/getFail0")
async def getFail0():
    return int(0)

@api.get("/getFail1")
async def getFail1():
    return int(0)

@api.get("/getPdMi")
async def getPdMi():
    return float(7.6)

@api.get("/getIlockPatchPanel")
async def getIlockPatchPanel():
    return int(12)

@api.get("/getVsel0")
async def getVsel0():
    return float(random.choice([5.0,0.0]))

@api.get("/getVsel1")
async def getVsel1():
    return float(random.choice([5.0,0.0]))

